Traceback (most recent call last):
  File "C:\Users\Sandra\anaconda3\envs\dataviz_venv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Sandra\anaconda3\envs\dataviz_venv\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Sandra\anaconda3\envs\dataviz_venv\lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\Sandra\anaconda3\envs\dataviz_venv\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Sandra\anaconda3\envs\dataviz_venv\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Sandra\anaconda3\envs\dataviz_venv\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Sandra\anaconda3\envs\dataviz_venv\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#----- Autocorrelaci√≥n--------------------------------------------------------------------------------------------------------
import numpy as np, pandas as pd
from statsmodels.graphics.tsaplots import plot_acf
import matplotlib.pyplot as plt


# Crear una figura con subplots
fig = make_subplots(rows=3, cols=2)

# Agregar los gr√°ficos a los subplots correspondientes
fig.add_trace(go.Scatter(y=df_tseries.value, mode='lines', line=dict(color='blue'), showlegend=False, hovertemplate='Value: %{y}'), row=1, col=1)
fig.add_trace(go.Scatter(y=df_tseries.value.diff(), mode='lines', line=dict(color='red'), showlegend=False, hovertemplate='Diff: %{y}'), row=2, col=1)
fig.add_trace(go.Scatter(y=df_tseries.value.diff().diff(), mode='lines', line=dict(color='green'), showlegend=False, hovertemplate='Diff Diff: %{y}'), row=3, col=1)

# Para agregar los gr√°ficos de autocorrelaci√≥n, se necesita calcular los valores de autocorrelaci√≥n
acf_values = acf(df_tseries.value, nlags=2080)
fig.add_trace(go.Scatter(y=acf_values, mode='lines', fill='tozeroy', line=dict(color='blue'), showlegend=False, hovertemplate='ACF: %{y}'), row=1, col=2)

diff1_values = df_tseries.value.diff()
acf_diff1_values = acf(diff1_values.dropna(), nlags=2080)
fig.add_trace(go.Scatter(y=acf_diff1_values, mode='lines', fill='tozeroy', line=dict(color='red'), showlegend=False, hovertemplate='ACF Diff: %{y}'), row=2, col=2)

diff2_values = df_tseries.value.diff().diff()
acf_diff2_values = acf(diff2_values.dropna(), nlags=2080)
fig.add_trace(go.Scatter(y=acf_diff2_values, mode='lines', fill='tozeroy', line=dict(color='green'), showlegend=False, hovertemplate='ACF Diff Diff: %{y}'), row=3, col=2)

# Agregar t√≠tulos a las gr√°ficas

fig.add_annotation(dict(text='Serie original', x=0.20, y=1.1, xref='paper', yref='paper', showarrow=False, font=dict(size=14)))
fig.add_annotation(dict(text='1er Orden de diferenciaci√≥n', x=0.15, y=0.66, xref='paper', yref='paper', showarrow=False, font=dict(size=14)))
fig.add_annotation(dict(text='2do Orden de diferenciaci√≥n', x=0.15, y=0.25, xref='paper', yref='paper', showarrow=False, font=dict(size=14)))

fig.add_annotation(dict(text='ACF de la Serie original', x=0.85, y=1.1, xref='paper', yref='paper', showarrow=False, font=dict(size=14)))
fig.add_annotation(dict(text='ACF del 1er Orden de diferenciaci√≥n', x=0.88, y=0.66, xref='paper', yref='paper', showarrow=False, font=dict(size=14)))
fig.add_annotation(dict(text='ACF del 2do Orden de diferenciaci√≥n', x=0.88, y=0.25, xref='paper', yref='paper', showarrow=False, font=dict(size=14)))
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[18], line 8[0m
[0;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[0;32m      7[0m [38;5;66;03m# Crear una figura con subplots[39;00m
[1;32m----> 8[0m fig [38;5;241m=[39m [43mmake_subplots[49m(rows[38;5;241m=[39m[38;5;241m3[39m, cols[38;5;241m=[39m[38;5;241m2[39m)
[0;32m     10[0m [38;5;66;03m# Agregar los gr√°ficos a los subplots correspondientes[39;00m
[0;32m     11[0m fig[38;5;241m.[39madd_trace(go[38;5;241m.[39mScatter(y[38;5;241m=[39mdf_tseries[38;5;241m.[39mvalue, mode[38;5;241m=[39m[38;5;124m'[39m[38;5;124mlines[39m[38;5;124m'[39m, line[38;5;241m=[39m[38;5;28mdict[39m(color[38;5;241m=[39m[38;5;124m'[39m[38;5;124mblue[39m[38;5;124m'[39m), showlegend[38;5;241m=[39m[38;5;28;01mFalse[39;00m, hovertemplate[38;5;241m=[39m[38;5;124m'[39m[38;5;124mValue: [39m[38;5;124m%[39m[38;5;132;01m{y}[39;00m[38;5;124m'[39m), row[38;5;241m=[39m[38;5;241m1[39m, col[38;5;241m=[39m[38;5;241m1[39m)

[1;31mNameError[0m: name 'make_subplots' is not defined

